/*globals history, document, window, jQuery */
/*!
	semanticPopup
	Copyright	Paul Wisniowski
	License		MIT
	Version		1.0.0

	http://psdhtml.me
*/
!function(a){"use strict";a.openPopup=function(t){a('a[data-popup="'+t+'"]').length&&(a('[class^=popup][data-title="'+t+'"]').addClass("shown").attr({focusable:!0,"aria-hidden":!1}),document.location.hash="!"+t,a(document.documentElement).addClass("popup-shown"))},a.fn.semanticPopup=function(){var t=a(document.documentElement),s=a(this);function e(){"pushState"in history?history.pushState("",document.title,window.location.pathname+window.location.search):window.location=window.location.href.replace(/#.*/,"")}return a(this).attr({focusable:!1,"aria-hidden":!0}).wrapInner('<div class="box-outer"><div class="box-inner"><div class="box-inset"></div></div></div>'),t.addClass("spi"),a(this).each(function(o){a(this).attr({"aria-labelledby":"popup-tab-"+(o+1),"aria-describedby":"popup-tab-"+(o+1),id:a(this).attr("data-title")}),a('[data-popup="'+a(this).attr("data-title")+'"]').attr({id:"popup-tab-"+(o+1),"aria-controls":a(this).attr("data-title"),"aria-haspopup":"true",href:"#"+a(this).attr("data-title")}),a('<a class="close" href="./">Close</a>').appendTo(a(this).find(".box-outer, .box-inset")),a(this).find('.close, button[type="reset"]').on("click",function(){return s.filter(".shown").removeClass("shown").attr({focusable:!1,"aria-hidden":!0}).addClass("unshown").delay(500).queue(function(){a(this).removeClass("unshown").dequeue()}),t.removeClass("popup-shown"),e(),!1}).prev().addClass("last-child"),a(this).addClass("ready")}),a("body").on("submit","form[data-popup]",function(){if(!a(this).is(".disabled"))return s.filter(".shown").removeClass("shown").attr({focusable:!1,"aria-hidden":!0}).addClass("unshown").delay(500).queue(function(){a(this).removeClass("unshown").dequeue()}),a('[class^=popup][data-title="'+a(this).attr("data-popup")+'"]').addClass("shown").attr({focusable:!0,"aria-hidden":!1}),t.addClass("popup-shown"),!1}),a(window).on("keydown",function(o){27===o.which&&(s.filter(".shown").removeClass("shown").attr({focusable:!1,"aria-hidden":!0}).addClass("unshown").delay(500).queue(function(){a(this).removeClass("unshown").dequeue()}),t.removeClass("popup-shown"),e())}),a(this)}}(jQuery);